name = "fwdjr"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

workers_dev = false
preview_urls = false

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "7341dcfd11d54d6b8cb1f328524a7b06"				#KV数据库id
