name = "djgkgcjjcjvkv"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

workers_dev = false
preview_urls = false

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "9f926a9a4a9448f887fcad1e350641ed"				#KV数据库id
